version: "3.8"

services:
  express-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=192.168.1.15
      - DB_PORT=5432
      - DB_NAME=mydb
    volumes:
      - ./backend:/usr/src/app
    networks: [app-net]

  react-frontend:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=/api
    stdin_open: true
    tty: true
    depends_on: [express-backend]
    networks: [app-net]

  

networks:
  app-net:
