version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"          # host 3001 → container 3001
    environment:
      - NODE_ENV=production
      - DB_USER=myuser       # Database username
      - DB_PASSWORD=mypassword # Database password
      - DB_HOST=172.17.0.1 # Use host.docker.internal to connect to local DB
      - DB_PORT=5432         # Database port
      - DB_NAME=mydb         # Database name
    volumes:
      - ./backend:/usr/src/app
    depends_on: []
    networks: [app-net]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"          # host 3000 → container 3000 (React dev)
    environment:
      - REACT_APP_API_URL=http://localhost:3001 
    volumes:
      - ./frontend:/usr/src/app
    stdin_open: true
    tty: true
    depends_on: [backend]
    networks: [app-net]

networks:
  app-net:
