apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
    spec:
      containers:
        - name: express-backend
          image: sanfara/express-backend:v42
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: "192.168.1.15"  # might not work in K3s; see NOTE below
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "myuser"
            - name: DB_PASSWORD
              value: "mypassword"
            - name: DB_NAME
              value: "mydb"
      nodeSelector:
            kubernetes.io/hostname: ceserverc

---
apiVersion: v1
kind: Service
metadata:
  name: express-backend-service
spec:
  selector:
    app: express-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
