name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push React image
        run: |
          docker build -t sanfara/nginx-reverse-proxy:v2 ./nginx
          docker push sanfara/nginx-reverse-proxy:v2

      - name: Build and push Express image
        run: |
          docker build -t sanfara/express-backend:v2 ./backend
          docker push sanfara/express-backend:v2

      - name: Run Tests
        run: |
          # Run your tests here, e.g., using Jest or Mocha for Node.js
          # npm install
          # npm test
